---
on:
  push:
    tags:
      - "*"

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: crosser/build-dpkg
        id: build
        with:
          args: --unsigned-source --unsigned-changes

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build.outputs.filename }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.filename }}
